### ISSUE TITLE
Send raw value instead of masked one

### ISSUE THREAD

**Issue by devnicolas1** [nurmuhammet-ali/nova-inputmask#1]
First of all, I want to thank you for the excellent package! Its surely helping us a lot.

Me and my team have a problem with how the values are being submitted after they are masked. We need the values to be submitted **without the mask**, so for example:
```php
NovaInputmask::make('Masked Field', 'masked')
    ->mask("999.999.999-99")
```

In this case, if I inputted the value `12345678900`, the mask would convert it to `123.456.789-00`. Thing is, I need the value submitted to the backend, validated, saved on the database and etc to be `12345678900`.

Is there any possible way of doing this that I'm missing? If not, how hard would be to implement it? I would be down to opening a PR if I had any minor help with the concepts that make it all work (although I never actually worked with Vue, but it shouldn't be that hard).

**Comment by nurmuhammet-ali** [comment]
@devnicolas1 Hello buddy, I understand, I also save number unmasked to db for validation purposes and so on.
Here how I do it:

```php
NovaInputmask::make(__('Customer phone'), 'customer_phone')
    ->mask("999.999.999-99")
    ->resolveUsing(fn () => mask_phone($this->customer_phone))
    ->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
        $model->{$attribute} = unmask_phone($request->input($attribute));
    })
```

Where my mask_phone() and unmask_phone are functions I created in helpers:

helpers.php
```php
function unmask_phone(string|int|float $phone): string
{
        return str_replace(['.', '-'], '', $phone);
}

function mask_phone(string|int|float $phone): string
{
          // Note that this function assumes that the integer value has exactly 11 digits. The function may produce unexpected results if the input value has a different length.
          return substr($integer, 0, 3) . '.' . substr($integer, 3, 3) . '.' . substr($integer, 6, 3) . '-' . substr($integer, 9, 2);
}
```

**Comment by nurmuhammet-ali** [comment]
@devnicolas1 feel free to reopen

**Comment by devnicolas1** [comment]
So, I currently have this piece of code:
```php
$cpfCnpjFormField = NovaInputmask::make('CPF / CNPJ', 'cpf_cnpj')
                ->mask("(999.999.999-99)|(99.999.999/9999-99)")
                ->onlyOnForms()
                ->creationRules('unique:clients')
                ->updateRules('unique:clients')
                ->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
                    $model->$attribute = $this->unmaskNumericValue($request->input($attribute));
                })
                ->rules(['required', 'numeric']);
```

I don't currently need to format the output, so that's why I'm not using `resolveUsing`. Although, using `fillUsing` has apparently having no effect on the input right now. Changing the field to `Text` and removing the `mask()` property (for obvious reasons) seems to make it work correctly (if I manually input the mask values, it still passes the validation).

Am I still missing something? I'm up to sending more information if its needed.

**Comment by devnicolas1** [comment]
To add context: `unmaskNumericValue` is a simple regex that simply removes everything that is not between 0 and 9. This part in specific is working just fine.

**Comment by nurmuhammet-ali** [comment]
@devnicolas1, I cannot fully understand. Let's chat via telegram, add me via username @nurmuhammetali

**Comment by nurmuhammet-ali** [comment]
@devnicolas1 By the way, I added support to save raw values.
